import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProviderWrapper from "./SessionProviderWrapper/page";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const myFont = localFont({ src: "../asset/fonts/DAGGERSQUARE.otf" });

export const metadata: Metadata = {
  title: "CROSSFIRE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
